### ISSUE TITLE
Curly brackets place the contents outside.

### ISSUE THREAD

**Issue by Koiane** [cortex-js/cortexjs.io#8] opened 2021-08-17 07:41 UTC
To reproduce: 
1. Open https://cortexjs.io/mathlive/demo/
2. Remove everything from the first box. 
3. Type "{", "1", "}"

Expected result: "{1}"
Actual result: "{}1"

The latex code is consistent with the result in the box, "\left\lbrace\right\rbrace1" (in other words, the problem is not a discrepancy between the boxes.)

The problem does not occur with hard brackets, for example "[1]". 

In addition, I'm wondering if there is something else wrong with the version of MathLive in the demo. When adding parentheses, they are simply added as "(...)", the standard non-scaling parentheses in latex. I would have expected them to use "\left(...\right)". Consider the visual difference between "(\frac{1}{2})" and "\left(\frac{1}{2}\right)".

**Comment by arnog** [comment] 2021-08-17 09:31
The regular brackets `(...)` are non-scaling because the mathfield in the demo doesn't have `smart-fence` on (to verify, add the `smart-fence` attribute to the `math-field`),   so this is expected behavior.
The other issue (the `1` being inserted after the closing bracket) is indeed a bug and tracked with https://github.com/arnog/mathlive/issues/1137

**Closed by arnog** 2021-08-17 09:31 UTC
